# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy static site to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # No npm install or build step needed!
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1F2671AB1E0A46CD9184CF0F31B72A88 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9DFC10D5A36F48B28926A3526614E182 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FFBEB6CC2FA94F8BBA84156D7C1D6148 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'another-training-test'
          slot-name: 'Production'
          package: .

          
